# Generated by Django 2.2.7 on 2019-11-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(max_length=10, verbose_name='Site Code')),
                ('delivery_type', models.IntegerField(choices=[(1, 'Single MPLS'), (2, 'Single Internet'), (3, 'MPLS + Internet'), (4, 'Double MPLS'), (5, 'Double Internet')], verbose_name='Type of delivery')),
                ('address', models.CharField(max_length=64, verbose_name='Site Address')),
                ('bandwidth', models.IntegerField(verbose_name='Bandwidth')),
                ('site_classification', models.IntegerField(choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Bronze')], verbose_name='Site Classification:')),
                ('instalation_date', models.DateField(verbose_name='Date when line will be installed on site?')),
                ('local_contact', models.CharField(max_length=64, verbose_name='???Contact to person on site???')),
                ('technical_contact', models.CharField(max_length=64, verbose_name='???Contact to person on site???')),
                ('lan_assistance', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Do you need assistance with LAN?')),
                ('voip_assistance', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Do you need VoIP on site?')),
                ('parrarelorhot', models.IntegerField(choices=[(1, 'Parallel move'), (2, 'Hot-cut ')], verbose_name='Parallel move or hot-cut ?')),
                ('company_name', models.CharField(max_length=64, verbose_name='Company Name:')),
                ('city', models.CharField(max_length=64, verbose_name='City:')),
                ('address_2', models.CharField(max_length=64, verbose_name='Address:')),
                ('post_code', models.CharField(max_length=64, verbose_name='Postal Code:')),
                ('country', models.CharField(max_length=64, verbose_name='Country:')),
                ('office_hours', models.IntegerField(choices=[(1, '7-17'), (2, '8-16'), (3, '24/7')], verbose_name='Office Hours:')),
                ('division', models.IntegerField(choices=[(1, 'Road'), (2, 'Air & Sea'), (3, 'Solutions')], verbose_name='Division:')),
                ('local_name', models.CharField(max_length=64, verbose_name='Local Contact Full Name:')),
                ('local_email', models.EmailField(max_length=254, verbose_name='Local Contact Email:')),
                ('local_phone', models.CharField(max_length=64, verbose_name='Local Contact Phone:')),
                ('technical_name', models.CharField(max_length=64, verbose_name='Technical Contact Full Name:')),
                ('technical_email', models.EmailField(max_length=254, verbose_name='Technical Contact Email:')),
                ('technical_phone', models.CharField(max_length=64, verbose_name='Technical Contact Phone:')),
                ('additional_information', models.TextField(null=True, verbose_name='Please provide here all information that could be necessary to successfully perform this deployment:')),
                ('request_instalatioon_date', models.DateField(verbose_name='Requested install date:')),
                ('go_live_date', models.DateField(verbose_name='Go-live date:')),
                ('white_collars_num', models.IntegerField(verbose_name='Number of white collars:')),
                ('blue_collars_num', models.IntegerField(verbose_name='Number of blue collars:')),
                ('contact_name', models.CharField(max_length=64, verbose_name='Full Name:')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('contact_phone', models.CharField(max_length=64, verbose_name='Phone:')),
                ('contact_name2', models.CharField(max_length=64, verbose_name='Full Name:')),
                ('contact_email2', models.EmailField(max_length=254, verbose_name='Email:')),
                ('contact_phone2', models.CharField(max_length=64, verbose_name='Phone:')),
                ('company_name2', models.CharField(max_length=64, null=True, verbose_name='Company Name:')),
                ('building_type', models.CharField(max_length=64, null=True, verbose_name='Building Type:')),
                ('floor', models.IntegerField(null=True, verbose_name='Floor:')),
                ('site_code2', models.CharField(max_length=64, null=True, verbose_name='Site Code:')),
                ('company_name3', models.CharField(max_length=64, null=True, verbose_name='Company Name:')),
                ('building_type3', models.CharField(max_length=64, null=True, verbose_name='Building Type:')),
                ('floor3', models.IntegerField(null=True, verbose_name='Floor:')),
                ('site_code3', models.CharField(max_length=64, null=True, verbose_name='Site Code:')),
                ('rack_space', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Do you have a space for a least 3 rack units per router?:')),
                ('cooling', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Is there cooling in the Server room?:')),
                ('power', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Is there power on site?:')),
                ('power_before_instalation', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='If no will you have power on site before install date?:')),
                ('power_backup', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Is there emergency back-up power for the equipment?:')),
                ('emergency_power', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Do you want help with building an emergency power?:')),
                ('lan_assistance2', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Help with LAN needed?:')),
                ('wireless', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Wireless LAN?:')),
                ('standard_wireless', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Standard Wireless?:')),
                ('telephone_service', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Do you want to deploy telephony services?:')),
                ('pstn_lines', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Are you using locat PSTN lines at the moment?:')),
                ('reason', models.CharField(max_length=64, null=True, verbose_name='If No: Please specify reason why?:')),
            ],
        ),
    ]
