# Generated by Django 2.2.7 on 2019-11-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbeportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevendor',
            name='site_classification',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=64, verbose_name='Site Classification:'),
        ),
    ]
