# Generated by Django 2.2.7 on 2019-11-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbeportal', '0002_auto_20191119_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevendor',
            name='additional_information',
            field=models.TextField(max_length=64, null=True, verbose_name='Please provide here all information that could be necessary to successfully perform this deployment:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='go_live_date',
            field=models.CharField(max_length=64, verbose_name='Go-live date:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='instalation_date',
            field=models.CharField(max_length=64, verbose_name='Date when line will be installed on site?'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='request_instalatioon_date',
            field=models.CharField(max_length=64, verbose_name='Requested install date:'),
        ),
    ]
