# Generated by Django 2.2.7 on 2019-11-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbeportal', '0004_auto_20191119_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevendor',
            name='cooling',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Is there cooling in the Server room?:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='emergency_power',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Do you want help with building an emergency power?:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='floor3',
            field=models.IntegerField(default=False, null=True, verbose_name='Floor:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='lan_assistance2',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Help with LAN needed?:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='power',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Is there power on site?:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='power_backup',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Is there emergency back-up power for the equipment?:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='power_before_instalation',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='If no will you have power on site before install date?:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='pstn_lines',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Are you using locat PSTN lines at the moment?:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='rack_space',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Do you have a space for a least 3 rack units per router?:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='reason',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='If No: Please specify reason why?:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='standard_wireless',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Standard Wireless?:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='telephone_service',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Do you want to deploy telephony services?:'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='wireless',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Wireless LAN?:'),
        ),
    ]
