# Generated by Django 2.2.7 on 2019-11-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbeportal', '0006_auto_20191120_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevendor',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='go_live_date',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='local_email',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='local_name',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='local_phone',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='request_instalatioon_date',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='technical_email',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='technical_name',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='technical_phone',
        ),
        migrations.AddField(
            model_name='sitevendor',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Here you can attache files:'),
        ),
    ]
