# Generated by Django 2.2.7 on 2019-11-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbeportal', '0007_auto_20191120_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevendor',
            name='delivery_type',
            field=models.CharField(choices=[('Single MPLS', 'Single MPLS'), ('Single Internet', 'Single Internet'), ('MPLS + Internet', 'MPLS + Internet'), ('Double MPLS', 'Double MPLS'), ('Double Internet', 'Double Internet')], max_length=64, verbose_name='Type of delivery'),
        ),
        migrations.AlterField(
            model_name='sitevendor',
            name='site_code',
            field=models.CharField(help_text='Code requested by Vendor Team', max_length=10, verbose_name='Site Code'),
        ),
    ]
