# Generated by Django 2.2.7 on 2019-11-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbeportal', '0008_auto_20191125_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevendor',
            name='file',
        ),
    ]
